---
resources:
- name: kubernetes
  type: git
  source:
    uri: git@github.com:bstick12/tracking.git
    branch: master
    tag_filter: "v*"
    private_key: ((private_key))

- name: tracking-ci
  type: git
  source:
    uri: git@github.com:bstick12/tracking.git
    branch: master
    private_key: ((private_key))

- name: kubo-release
  type: git
  source:
    uri: git@github.com:bstick12/kubo-release.git
    branch: master
    private_key: ((private_key))

jobs:
- name: create-feature
  public: true
  plan:
  - get: kubernetes
    trigger: true
  - get: kubo-release
  - get: tracking-ci
  - task: create-feature-branch
    file: tracking-ci/create-feature.yml
  - put: kubernetes
    params:
      repository: tracking-feature

